name: Deploy Laravel API

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Laravel API Only
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Sync API to Server (exclude admin & shop)
        run: |
          rsync -avz \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude 'admin' \
            --exclude 'shop-frontend' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}

      - name: Write .env file on server from secret
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "${{ secrets.ENV_CONTENT }}" > ${{ secrets.DEPLOY_PATH }}/.env
          EOF

      - name: Run post-deploy script
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e

            cd ${{ secrets.DEPLOY_PATH }}

            composer install --no-interaction --prefer-dist --optimize-autoloader

            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            chown -R www-data:www-data .
          EOF
