name: Deploy Admin Vue App

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Vue Admin App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Clean remote folder before deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf ${{ secrets.ADMIN_DEPLOY_PATH }}/*"

      - name: Rsync full admin project to server
        run: |
          rsync -avz \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./admin/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.ADMIN_DEPLOY_PATH }}

      - name: Run npm install and build on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.ADMIN_DEPLOY_PATH }}
            npm install
            npm run build
          EOF

      - name: Fix permissions
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            sudo chown -R www-data:www-data ${{ secrets.ADMIN_DEPLOY_PATH }}
          EOF
